spring:
  application:
    name: Backend_Developer
  datasource:
    url: JDBC:mysql://localhost:3306/AuthenticationS_db?createDatabaseIfNotExist=true
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: 8085


logging:
  level:
    org:
      springframework:
        security: DEBUG


    level:
         org.springframework.security: TRACE